id: P7452310F
initial_creation_type: input
source_metadata:
  title: Namkha Tsewang Chokdrup Series
  language: en
  description: 'Texts by and about Namkha Tsewang Chokdrup (nam mkha’ tshe dbang mchog
    grub, b. 1744) of Dzogchen Monastery:'
  volume:
    c1c4247fb7224dd2a4c262c47329d165:
      title: The Prayer for the Wrathful Guru Takhyung Barwa from the Heart Essence
        of the Vast Expanse
      parent: Prayers
created_at: '2022-03-01T00:58:54.049214'
last_modified_at: '2022-03-01T00:58:54.049219'
